### ISSUE TITLE
Crash on spy_on

### ISSUE THREAD

**Issue by OlegAnghelov** [pivotal/cedar#321] opened 2015-03-25 16:00 UTC
Class: CDRSpy.mm
Method and rows:
```objective-c
- (void)forwardInvocation:(NSInvocation *)invocation {
    [self.cedar_double_impl record_method_invocation:invocation];
    int method_invocation_result = [self.cedar_double_impl invoke_stubbed_method:invocation];

    [invocation copyBlockArguments];
    [invocation retainArguments]; //crashes here, EXC_BAD_ACCESS
```

Printing the invocation:
```
<NSInvocation: 0x7fe75a549480>
return value: {v} void
target: {:} 8ä	
argument 1: {@} 0x1110d88e9
argument 2: {@} 0x108ff7268
```

Reason:
```objective-c
  spy_on(product);
  <some code>

  product should have_received(@selector(setObject:forKeyedSubscript:));
```

Comment: `product` comes from `RLMObject` from Realm database framework (http://realm.io)

**Comment by akitchen** [comment] 2015-03-26 03:32
Hi @OlegAnghelov 

Thank you very much for reaching out about this. Realm support matters to us, we will try to look into it soon.  If you gain any deeper insight into what's going on we'd really like to hear about it.

**Comment by akitchen** [comment] 2015-03-26 03:36
Cross-posted to https://www.pivotaltracker.com/story/show/91156994

**Comment by akitchen** [comment] 2015-03-26 04:53
@OlegAnghelov could you post more of an example of what you are trying to test with Realm?

How are you providing and using the RLMObject in this test?

**Comment by akitchen** [comment] 2015-03-26 05:44
My test case passes when run with the latest releases of Cedar and Realm.  Please share more info or close the issue if you can no longer reproduce.
```
#import <Cedar/Cedar.h>
#import <Realm/Realm.h>

using namespace Cedar::Matchers;
using namespace Cedar::Doubles;

@interface Cat : RLMObject
@property (nonatomic, copy) NSString *name;
@property (nonatomic) BOOL rescued;
@end

@implementation Cat
@end

SPEC_BEGIN(RealmCompatibilitySpec)

fdescribe(@"Interacting with Realm objects", ^{

    describe(@"using custom subscripting setter syntax when spying", ^{
        it(@"should be possible", ^{
            Cat *theo = [[Cat alloc] init];
            theo.name = @"Thelonious";

            spy_on(theo);
            theo[@"rescued"] = @YES;

            theo should have_received(@selector(setObject:forKeyedSubscript:));
            theo should have_received(@selector(setObject:forKeyedSubscript:)).with(@YES, @"rescued");
        });
    });

});

SPEC_END
```

**Comment by OlegAnghelov** [comment] 2015-03-26 10:36
Before we proceed, it is important to know the following:
Imagine we have class BaseModel:NSObject, and a subclass Product:BaseModel.
BaseModel has a method -(void)foo.
Product has a method 
```
- (void)start {
  [self foo];
}
```

Does Cedar support 
```
Product *product = [[Product alloc] init];
spy_on(product);
[product start];

product should have_received(@selector(foo));
```

So basically can we spy on a object from child-class and check if a method from superclass was called?

**Comment by jeffh** [comment] 2015-03-31 03:33
Cedar does capture internal method calls, but there are a lot of edge cases where it doesn't. It's better to not rely on that behavior because of that.

**Comment by akitchen** [comment] 2015-04-14 21:08
The edge cases @jeffh refers to have to do mainly with KVC and KVO, which shouldn't be tested via spying anyways.  They should be tested per their side effects.

I was never able to repro your crash, and my test cases using Realm passed.  Please open a new issue with more example code if you run into something.  Thanks!

**Closed by akitchen** 2015-04-14 21:08 UTC
